version: "3.3"
services:
  bot:
    container_name: python_bot
    env_file: ./.env
    build: .
    networks:
      - database
  mongo:
    image: mongo
    container_name: discord_bot_mongo
    networks:
      - database
    volumes:
      - ./data:/data/db

networks: 
  database: